export interface asset{
    Assetid : number;
    SerialNo : string;
    Branch : number;
    Brand : string;
    Type : number;
    Model : string;
    Processor_Type : string;
    Monitor_Type : string;
    Range_Type : string;
    Battery_Type : string;
    Battery_Ampere : string;
    Battery_Capacity : string;
    GraphicsCard : string;
    Optical_Drive : string;
    HDD : string;
    RAM : string;
    Inches : string;
    Port_Switch : string;
    Nos : number;
    Specification : string;
    Vendorid : number;
    Status : number;
    Remarks : string;
    Created_at : string;
    InvoiceDate : string;
    Warranty_Till : string;
    Invoice_No : string;
    Location : number;
    Uid : string;
    // Description : string;
    Branches : string;
    TypeName : string;
    Vendors : string;
    StatusName : string;
    totalrecord : number;
    LocationName : string;

}